export const projects = [
  {
    id: "01",
    title: "Senari Software Solution",
    tag: "Software / Collaboration",
    year: "2026",
    href: "https://github.com/fb3nitez/senari-software-solution",
    desc: "A collaborative software solution project. The public GitHub metadata was not available during this update, so the card stays intentionally concise.",
  },
  {
    id: "02",
    title: "Valentines App",
    tag: "TypeScript / React",
    year: "2026",
    href: "https://github.com/jp-pacho-ts/valentines-app",
    desc: "Interactive Valentine's experience built with React, TypeScript, Vite, Radix UI components, GSAP, and form tooling.",
  },
  {
    id: "03",
    title: "Gorilla Motors",
    tag: "HTML / Vehicle Platform",
    year: "2026",
    href: "https://github.com/jp-pacho-ts/gorilla-motors",
    desc: "Used-vehicle website mockup with inventory filters, a loan calculator, and a sell or trade-in appraisal flow.",
  },
  {
    id: "04",
    title: "Espazio Website",
    tag: "HTML / CSS / JavaScript",
    year: "2026",
    href: "https://github.com/jp-pacho-ts/espazio-website",
    desc: "Mockup website for Espazio Tacloban, highlighting local art, food, history, and Eastern Visayas heritage.",
  },
  {
    id: "05",
    title: "Optivex App",
    tag: "React / Three.js",
    year: "2026",
    href: "https://github.com/jp-pacho-ts/optivex-app",
    desc: "React and Vite app using routing, Tailwind tooling, and Three.js for a more visual web experience.",
  },
  {
    id: "06",
    title: "BookBridge System",
    tag: "Next.js / Prisma",
    year: "2026",
    href: "https://github.com/jp-pacho-ts/book-brigde-system",
    desc: "Ebook subscription prototype built with Next.js, TypeScript, Tailwind CSS, Prisma ORM, and PostgreSQL.",
  },
  {
    id: "07",
    title: "CapstoneVault",
    tag: "Django / Machine Learning",
    year: "2025",
    href: "https://github.com/jp-pacho-ts/CapstoneVault",
    desc: "Academic capstone repository with role-based access, upload approval, TF-IDF + SVM classification, PDF viewing, and research trend visualization.",
  },
  {
    id: "08",
    title: "iStream Attendance System",
    tag: "Attendance / System",
    year: "2026",
    href: "https://github.com/jp-pacho-ts/istream-attendance-system",
    desc: "Attendance system project for iStream workflows. The repo was not publicly discoverable from GitHub API/search during this update.",
  },
  {
    id: "09",
    title: "Juicy Loyalty",
    tag: "Company / Loyalty",
    year: "2026",
    href: "https://github.com/getJuicy/juicy-loyalty",
    desc: "Company loyalty project from Rooche Digital Web Design under the getJuicy GitHub organization.",
  },
  {
    id: "10",
    title: "EvoGolf Members App",
    tag: "Company / Members App",
    year: "2026",
    href: "https://github.com/getJuicy/EvoGolfMembersApp",
    desc: "Company members app project for Evolution Golf from Rooche Digital Web Design under the getJuicy GitHub organization.",
  },
];

export const stack = [
  { name: "TypeScript", devicon: "devicon-typescript-plain colored" },
  { name: "JavaScript", devicon: "devicon-javascript-plain colored" },
  { name: "React", devicon: "devicon-react-original colored" },
  { name: "Next.js", devicon: "devicon-nextjs-original" },
  { name: "Node.js", devicon: "devicon-nodejs-plain colored" },
  { name: "PostgreSQL", devicon: "devicon-postgresql-plain colored" },
  { name: "Neon DB", abbr: "NEON" },
  { name: "Prisma", abbr: "ORM" },
  { name: "NextAuth", abbr: "AUTH" },
  { name: "Tailwind CSS", devicon: "devicon-tailwindcss-plain colored" },
  { name: "shadcn/ui", abbr: "UI" },
  { name: "Radix UI", abbr: "RX" },
  { name: "Stripe", abbr: "PAY" },
  { name: "Shopify", devicon: "devicon-shopify-plain colored" },
  { name: "Docker", devicon: "devicon-docker-plain colored" },
  { name: "Fly.io", abbr: "FLY" },
];
